### ISSUE TITLE
ไม่สามารถพิมพ์ ๘ หรือ _ ได้ ใน Switch.Input.Language V.1.1 WIN 7-10

### ISSUE THREAD

**Issue by shinrainhawk** [sumonchai/Switch-Input-Language#1]
ไม่สามารถพิมพ์ ๘ หรือ _ ได้ ใน Switch.Input.Language V.1.1 WIN 7-10 บน windows 10 x64 v.1511
กลายเป็นเปลี่ยนภาษาแทน

**Comment by sumonchai** [comment]
แก้ไขแล้วครับ ทดลอง ติดตั้งใชงานตัวใหม่ครับ
